name: build

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: dotnet build --verbosity minimal --configuration Release --no-restore -p:TreatWarningsAsErrors=true
      
    - name: Test
      run: dotnet test --verbosity minimal --configuration Release --no-restore --no-build --collect:"XPlat Code Coverage" --results-directory ./coverage
        
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        format: cobertura
        file: "coverage/**/coverage.cobertura.xml"
